name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Test job - must pass before deployment
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Notify test failure
        if: failure()
        run: |
          curl -H "Title: ☠️ Radioactive Froggies Deploy Failed" \
               -H "Tags: warning,x" \
               -H "Priority: high" \
               -d "Tests failed - deployment blocked!

          Commit: ${{ github.event.head_commit.message }}

          By: ${{ github.event.head_commit.author.name }}

          Check logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
               https://ntfy.sh/radioactive-froggies

  # Deploy job - only runs if tests pass
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Send notification to ntfy.sh
        if: success()
        run: |
          curl -H "Title: 🐸☢️ Radioactive Froggies Updated!" \
               -H "Tags: frog,video_game,rocket" \
               -H "Priority: default" \
               -H "Actions: view, Open Game, ${{ steps.deployment.outputs.page_url }}" \
               -d "New deployment successful!

          Commit: ${{ github.event.head_commit.message }}

          By: ${{ github.event.head_commit.author.name }}

          Play now: ${{ steps.deployment.outputs.page_url }}" \
               https://ntfy.sh/radioactive-froggies
